title: DeL-TaCo
description: Multitask robotic policies conditioned on both demonstrations and language
theme: just-the-docs

url: https://deltaco-robot.github.io

aux_links:
  PDF: https://openreview.net/pdf?id=4u42KCQxCn8
  Poster: files/iclr_poster_v1_1.pdf
  Env Code: https://github.com/Alacarter/roboverse-deltaco
  Training Code (coming soon): /

callouts:
  update:
    title: Update
    color: yellow
