title: DeL-TaCo
description: Multitask robotic policies conditioned on both demonstrations and language
theme: just-the-docs

url: https://deltaco-robot.github.io

aux_links:
  PDF: https://arxiv.org/pdf/2210.04476.pdf
  Poster: files/iclr_poster_v1_1.pdf
  Env Code: https://github.com/Alacarter/roboverse-deltaco
  Training Code: https://github.com/Alacarter/deltaco

callouts:
  update:
    title: Update
    color: yellow
